name: Site

on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch Github Release Asset
        uses: dsaltares/fetch-gh-release-asset@0.06
        with:
          repo: cobalt-org/cobalt.rs
          file: cobalt-v0.19.2-x86_64-unknown-linux-gnu.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build site
        run: |
          tar xfv cobalt-*
          ./cobalt build
